### ISSUE TITLE
Module

### ISSUE THREAD

**Issue by FlorijonG** [CCBlueX/LiquidBounce-Issues#101]
Man kann eigene Module hinzufügen die ihr ablehnt.

**Comment by WistarWolf** [comment]
Oder man könnte eigene Sachen aufm Desktop anzeigen lassen ^^ z.B. Die FPS anzeigen lassen und dann anzeigen wie das aussieht und wo es ist ^^

**Comment by Marco-MC** [comment]
Raff ich nicht? xd
Auf jedenfall giebt es dann in der b24 ein ScriptSystem namens LiquidScript. Die leute die sich dann mit der Script Sprache auseinander gesetzt haben, können dann irge eigenen Scripts machen. Klar kann man nicht so wirklich viel machen. Aber Sachen wie Speeds, FPS Anzeige, LongJumps, movement technisches wird dann machbar sein. Aber so Sachen wie ClickGUIs oder so nicht. Es ist nämlich nicht so leicht eine eigene ScriptSprache zu programieren. :)

https://github.com/CCBlueX/LiquidBounce-Issues/issues/99

Ich close dann mal diesen Issue.

**Comment by WistarWolf** [comment]
Ist dann auch sowas wie Coodinaten, ServerIP anzeigen etc möglich? :)

**Comment by Marco-MC** [comment]
Ja wie du sieht bei values:

server.ip = not setable
player.ping = not setable
screen.fps = not setable

und mit 
mcfont.drawString = int(x) = int(y) int(color) boolean(shadow) string(text) kannst du dann den text rendern

So wäre das dann als Script:

```
scriptName = "MoreDisplay";
scriptVersion = 0.1;
scriptAuthor = "Marco_MC";

registerModule(MoreDisplay, Render) {

	onDraw2D {
		mcfont.drawString = 2 =- 30 true Ping: $player.ping$
		mcfont.drawString = 2 =- 20 true FPS: $server.ip$
		mcfont.drawString = 2 =- 10 true FPS: $screen.fps$
	}
}
```

**Comment by WistarWolf** [comment]
<3 Verstehe ich zwar noch nicht ganz aber ich werde es lernen <3 Kann man auch einstellen wir groß das Wort  ist /wo sie angezeigt wird? Sry ich kann net coden :D
