### ISSUE TITLE
Auto/Sofort Neu verbindungs Button

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce-Issues#103]
Ein Button unter Back to title Screen. Einmal einen Reconnect now und ein Auto reconnect Button. Reconnect now = Wenn man das drückt verbindet man sofort neu und muss nicht erst in den Multiplayer Screen. Auto reconnect = Man kann es (de-)aktiviern und dann wird man alle 5 Sekunden oder so automatisch neu verbunden.

**Comment by Marco-MC** [comment]
Added.
