### ISSUE TITLE
Script als Modul Einstellen

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce-Issues#107]
Dass man Scripte nichtnur als Module machen kann sonder auch als Einstellungsoption von einem Module. Und ist es nöglich hinzuzufügen das man dann bei den Scripten datum und uhrzeit anzeigen lassen kann?

**Comment by Marco-MC** [comment]
Nein, es wird nicht möglich sein z.B sich als neuer SpeedType in das SpeedModul einzuklinken.
Das mit der Zeit, kann ich mal machen.
#99
