### ISSUE TITLE
Jigsaw-like rightclick menu for lists

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce-Issues#109]
c:

**Comment by WistarWolf** [comment]
Was ist damit gemeint?

**Comment by SenkJu** [comment]
https://gyazo.com/26dba9e07e7dd5dd910a988c55b9654b

**Comment by Marco-MC** [comment]
Nein, werde ich nicht hinzufügen da das einfach aus meiner Sicht komplett scheiße ist wenn man sich erstmal durch die ganzen SpeedModes klicken muss etc. Wenn man dann beim richtigen SpeedMode ist und ihr klickt dann ausversehen doch nocheinmal drauf könnt ihr erstmal nochmal dort hinklickern.
