### ISSUE TITLE
Gerordnete ClickGUI einstellungen

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce-Issues#112]
Könnte man einfügen dass man die z.B. Speed Modes so Ordnet wie z.B. in Xanax https://i.gyazo.com/017f03064cc02114489e6f54c10a17cb.gif ? Oder das man nicht auf Modes rechtsklick darauf macht sonder auf AAC Speeds und dann werden die AAC Speeds aufgelistet oder rechtsklick auf NCP Speeds und dann werden die NCP Speeds aufgelistet. Und bei Fly die ganzen Fly Modes usw.
(PS: Die letzet Issues dazu hab ich geschlossen weil sie eh keiner mehr lesen wird.)
Quelle/Gif ausschnitt: https://www.youtube.com/watch?v=eHqu96_22aA Mintue 1.47

**Comment by TheRealDAT** [comment]
Jo, hast deine Idee mit meiner kombiniert das müsste echt sein. Aber bei was soll man bei Fly ordnen?

**Comment by WistarWolf** [comment]
Die Fly Modes?

**Comment by Marco-MC** [comment]
Das würde bei dem Null Design und dem LiquidBounce Design echt beschissen aussehen...
Sorry, aber ne.

**Comment by WistarWolf** [comment]
OK
