### ISSUE TITLE
Chat Commands (Bug)

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce-Issues#113]
Wenn man Ingame auf ein Wort Klickt womit man einen Command auslöst (Bei Party Anfragen von Plugins zum Beispiel) passiert nichts. Bitte fixen

**Comment by Marco-MC** [comment]
#49

**Comment by Marco-MC** [comment]
Fixed with the upgrade to 1.8.8 of H6. ^^
