### ISSUE TITLE
Server Versions Anzeige.

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce-Issues#115]
Im Multiplayer menu könnte neben den Server stehen welche Server Version sie habe. Wie in Wurst zum Beispiel.

**Comment by Marco-MC** [comment]
Höhö. Wurst.

**Comment by WistarWolf** [comment]
:D

**Comment by Marco-MC** [comment]
Auf jedenfall ist das relativ unnötig, da man per .serverinfo auch die Server Version sehen kann. Also würde das nur das Design zerstören.

**Comment by WistarWolf** [comment]
Ok ist auch wahr ^^
