### ISSUE TITLE
ModuleCleaner Module

### ISSUE THREAD

**Issue by Linus789** [CCBlueX/LiquidBounce-Issues#144]
Removes unnecessary modules from the list at the right of the screen. For example: Brightness

**Comment by Marco-MC** [comment]
Giebt es schon: https://github.com/CCBlueX/LiquidBounce-Issues/issues/22

**Comment by scorpion3013** [comment]
Marco, er meint das man Module aus der Arraylist entfehren bzw ausblenden kann.

**Comment by Marco-MC** [comment]
Oh. Naja egal. Werde das eh net adden.
