### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce-Issues#150]
Bugs die ich gefunden habe:

- Critical Tags am anfang groß schreiben
- Targets das blaue fixen
- Chams fixen
- Das TNTBlock Modul blockt TNT egal wo es auf der map ist. Bitte machen dass es nur im explosions radius blockt.
- AutoSword geht immernoch nicht richtig
- Wenn man unter HUD Armor an hat und ins wasser geht, Bugs die Armor Leiste rum.
- ChestStealer bugt die Items öfters mal zurück

Weiter Bugs habe ich noch nicht gefunden. Wenn ich weiter finde, werde sie melden.

**Comment by Marco-MC** [comment]
1. Changed
2. Fixed
3. Fixed
4. Fixed
5. Was geht denn daran nicht? Auf jedenfall kann ich da nichts fixen, da dass nur checkt welches Item am meistens Damage macht im Inventar und dann dahin moved.
6. Fixed
7. Liegt an InventoryCleaner. Fixe ich aber das wenn InventoryCleaner aktiviert ist nur die Items rausgezogen werden die InventoryCleaner nicht wegwirft.

**Comment by WistarWolf** [comment]
1. OK
2. OK
3. OK
4. OK
5. Ich hab gesagt bekommen das AutoSword net geht. Selber hab ich es nicht getestet.
6. OK
7. OK
