### ISSUE TITLE
make discord rpc deactivatable

### ISSUE THREAD

**Issue by Henriks9** [CCBlueX/LiquidBounce-Issues#2177]
make discord rpc deactivatable

**Comment by Teals53** [comment]
lol just disable discord game option xd

**Comment by kawaiinekololis** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2806

**Comment by superblaubeere27** [comment]
You can just disable it in Discord :o

**Comment by Henriks9** [comment]
No :c 
Pls add <3

**Comment by Litely1222** [comment]
delete folder name discord on liquidbounce.jar
