### ISSUE TITLE
(einstellbare) Priorisierung von Targets in der Killaura

### ISSUE THREAD

**Issue by henrydatei** [CCBlueX/LiquidBounce-Issues#2598]
Wäre es möglich, dass man eine Option einbaut, mit der man bestimmte Ziele, zum Beispiel Spieler, zuerst angreift und erst, wenn alle Spieler aus der Range sind, die anderen eingestellten Targets, also zum Beispiel Mobs.

Hintergrund dessen ist der Spielmodus "VampireZ" auf Hypixel, bei dem man als Überlebender gegen Massen an Zombies und einige andere Spieler (Vampire) kämpft. In der Regel kommen Zombies und "Vampire" in einem großen Haufen, aber die Zombies sind nicht das Problem, sondern die wenigen "Vampire". Deswegen wäre es nützlich, wenn die Killaura zuerst die "Vampire" erledigt und sich dann den Zombies zuwendet.

**Comment by 1zun4secondary** [comment]
https://github.com/CCBlueX/LiquidBounce-Issues/issues/3293
