### ISSUE TITLE
[FEATURE] Füge AzureWare GUI hinzu

### ISSUE THREAD

**Issue by cancerousname69** [CCBlueX/LiquidBounce-Issues#2955]
**Describe your feature request.**
Add azureware styled gui

**Additional context**
it really looks sexy.

**Comment by Marco09MC** [comment]
Es wäre möglich für uns das GUI nachzumachen, daher lasse ich diesen Issue einfach offen.
Wir werden aber definitiv nicht die GUI skidden.
