### ISSUE TITLE
[Recode] Recode Liquidlauncher (Senk ju)

### ISSUE THREAD

**Issue by barbiehunter** [CCBlueX/LiquidBounce-Issues#2990]
1Liquidlauncher Recoden (komplett), da es soviele mit bugs gibt mit Laden, Settings (Minecraft und Liquidbounce).

-Dark mode adden
-Maybe alt liste adden
-Andere sachen maybe die mir nicht einfallen gerade.

**Comment by RealFantaCoke** [comment]
Warum nutzt man bitte den LiquidLauncher, wenn man damit aufgrund der vielen Bugs nicht richtig klar kommt? Ich sehe keinen nützlichen Vorteil außer der automatischen ClientUpdates.
