### ISSUE TITLE
[BUG] ESP Shader White Screen

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce-Issues#3025]
**Describe the bug**
When you enable the ESP module and change the mode to Shader Outline OR Shader Glow you will get a white screen.

**To Reproduce**
1. Enable ESP
2. Set ESP-mode to Shader Outline / Shader Glow

**Screenshots**
No screenshots taken

**Additional information:**
 - OS: Windows 10 | 1903
 - LiquidBounce Build Version: b63
 - Minecraft Version: 1.8.9

Happened to my friend and me - we don't had Fast Render enabled when the bug occurred.
I think it's since b63 but didn't tried it yet in b62 or lower.

**Comment by SenkJu** [comment]
Disable antialiasing in video settings.

**Comment by RealFantaCoke** [comment]
> Disable antialiasing in video settings.

Allright, will try it later. If Antialiasing is really the error then maybe add a notice for the users who don't know it or auto-disable it when enabling ESP.

**Comment by RealFantaCoke** [comment]
> Disable antialiasing in video settings.

It didn't fixed the bug, i tried it and it was already disabled.
Even enabling it won't fix it.

There must be another reason why ShaderESP doesn't works.

**Comment by scorpion3013** [comment]
That happens when a shader is enabled via optifine.

**Comment by RealFantaCoke** [comment]
> That happens when a shader is enabled via optifine.
> And a whitescreen isnt the only behavior you can get from this:
> the thing with this effect is, it stays after turning off esp.
> example: https://streamable.com/o104f

Oh, that's new ... normally, when i turn off ESP then it goes back to normal.
