### ISSUE TITLE
Need more bypasses

### ISSUE THREAD

**Issue by 6alpha9** [CCBlueX/LiquidBounce-Issues#3097]
**Describe your feature request.**
Currently LBs killaura is bypassing : aac, watchdog, mac and others. 
But its get flagged by: metrix, intave, even ncp.
You cant make config because these are heuristics flags.

**Comment by Soulplexis** [comment]
Killaura flags on NCP For "Combined_improbable (Fight.speed)"
sometimes the interactautoblock / autoblock bugs out and flags anticheat with a check for it such as PAC

**Comment by coolpvpv1** [comment]
> **Describe your feature request.**
> Currently LBs killaura is bypassing : aac, watchdog, mac and others.
> But its get flagged by: metrix, intave, even ncp.
> You cant make config because these are heuristics flags.

idk how more bypasses is even a issue and matrix falses more then it detects i pvped one time with matrix anticheat on and i falsed killlaura hitbox reach autoclicker etc legit pvping in about 2 mins so idk if you can bypass a anticheat that falses more then it detects and i dont see much servers with intave other then like 2 and ncp it takes alot of flags to set off alerts to admins like 1000 vls to set off admin alerts etc

**Comment by SenkJu** [comment]
We will only make bypasses for AntiCheats which are actually being used by servers.

**Comment by Teals53** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3134
