### ISSUE TITLE
[BUG] Esp bug

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce-Issues#3126]
![2019-09-05_00 18 43](https://user-images.githubusercontent.com/13446881/64292298-c59af900-cf72-11e9-80d2-6ee35d202d71.png)
![2019-09-05_00 18 44](https://user-images.githubusercontent.com/13446881/64292301-c59af900-cf72-11e9-8ab9-64b1206494e3.png)

**Comment by Teals53** [comment]
but its gonna fixed when i do f11 .d

**Comment by Teals53** [comment]
![2019-09-05_00 20 58](https://user-images.githubusercontent.com/13446881/64292439-14e12980-cf73-11e9-834b-d7c765ec88f4.png)

**Comment by Teals53** [comment]
interesting xd

**Comment by SenkJu** [comment]
What graphics card are you using?

**Comment by Teals53** [comment]
Gt 730 fermi 2 gb

**Comment by Tcm9** [comment]
to old is it not. My graphics card are a Nvidia geforce gt 230m. The graphics card works great, and everything works fine.

**Comment by Teals53** [comment]
And i see this bug first time about all four years and i fix that after format my pc xd but i just want report that
