### ISSUE TITLE
[FEATURE] Criticals HypixelPacket

### ISSUE THREAD

**Issue by Jxzh123** [CCBlueX/LiquidBounce-Issues#3164]
Criticals HypixelPacket no damage
Jump Hop Not conducive to combat
Can you fix this mode?

**Comment by SenkJu** [comment]
Could you describe your problem more clearly?

**Comment by Soulplexis** [comment]
I think he is saying HypixelPacket doesn't do critical hits, and Hop mode isn't very helpful

**Comment by Jxzh123** [comment]
I am Chinese,English are not very good
HypixelPacket Mode Not very useful in the hypixel server
Hop Mode Make speed work abnormally

**Comment by icewormy3** [comment]
> Criticals HypixelPacket no damage
> Jump Hop Not conducive to combat
> Can you fix this mode?
Criticals HypixelPacket does actually do critical hits, but its delayed in a certain way and its patched on hypixel (Use packet mode if you want all of your hits to be critical hits)
ofc hop mode is going to slow you in combat, thats how it works

**Comment by Jxzh123** [comment]
> > 严重性HypixelPacket没有损坏
> > 跳跃跳跃不利于战斗
> > 您可以解决此模式吗？
> 
> Criticals HypixelPacket实际上确实会产生关键命中，但是它以某种方式延迟并且已在hypixel上进行了修补（如果您希望所有命中都是关键命中，请使用数据包模式）
> 
> off跳频模式会减慢您的战斗速度，这就是它的工作原理
Packet mode does not bypass for hypixel
