### ISSUE TITLE
[BUG] StorageEsp X-Ray Weird 

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce-Issues#3384]
when I open the storageesp, the items in my hands get brighter but why ?

![image](https://user-images.githubusercontent.com/13446881/71772060-7a5f1a00-2f55-11ea-9183-07f4a58c5daf.png)

**Comment by Teals53** [comment]
And when i open xray my brightness settings get %100

my brightness settings is 0 now

![image](https://user-images.githubusercontent.com/13446881/71772188-f4909e00-2f57-11ea-8be4-4ea9b93ce07d.png)

then i open and reclose xray, reclose or not it doesnt matter when you open xray its set %100 automatically but why 🤔

![image](https://user-images.githubusercontent.com/13446881/71772193-0ffba900-2f58-11ea-8222-0e71d1f1ed45.png)

**Comment by kawaiinekololis** [comment]
Which StorageESP mode are you using?

**Comment by Teals53** [comment]
![image](https://user-images.githubusercontent.com/13446881/72563513-e713d600-38be-11ea-8e0c-8bc2dab7bb1a.png)
i forgot name but this one from standart settings

**Comment by kawaiinekololis** [comment]
Looks like ShaderGlow

**Comment by Teals53** [comment]
![image](https://user-images.githubusercontent.com/13446881/72563694-440f8c00-38bf-11ea-83fb-f9488fdf3533.png)

**Comment by kawaiinekololis** [comment]
I'm not able to reproduce it myself ... so yeah any logs? etc

**Comment by Teals53** [comment]
which log i need send ?

**Comment by Teals53** [comment]
maybe its fixed from b70 its not do this anymore

**Comment by Teals53** [comment]
bruh xd
