### ISSUE TITLE
[FEATURE] Auto open chat on pressing . 

### ISSUE THREAD

**Issue by Soulplexis** [CCBlueX/LiquidBounce-Issues#3391]
**Describe your feature request.**
if you press / it will open chat and automatically input /
for commands.
it should do it for . commands too 

**Additional context**

**Comment by xHackerBey-Egemen** [comment]
like Flux

**Comment by Tcm9** [comment]
The only thing that needs to be added is in the controls point-commands.
![image](https://user-images.githubusercontent.com/31276706/71843958-5fabb300-30c5-11ea-9a08-a66732f19893.png)
the rest exists.

**Comment by superblaubeere27** [comment]
This is already a Minecraft Feature. Please close this issue because I think you got what you want ;D

**Comment by Soulplexis** [comment]
> This is already a Minecraft Feature. Please close this issue because I think you got what you want ;D

it's not been made

**Comment by whycantiusemyname** [comment]
> This is already a Minecraft Feature. Please close this issue because I think you got what you want ;D
This is already a Minecraft Feature,but its not a LB feature.

**Comment by NetherStar64** [comment]
Should be closed, it's to useless
