### ISSUE TITLE
[BUG] Autoweapon

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce-Issues#3548]
**Describe the bug**
Not working (spoofmode disabled)

**To Reproduce**

**Screenshots**

**Additional information:**
 - LiquidBounce Build Version [e.g. b61]
 - Minecraft Version [e.g. 1.8.9]

**Comment by superblaubeere27** [comment]
Works for me. How to reproduce it?

**Comment by yorik100** [comment]
> 
> 
> Works for me. How to reproduce it?

Any server, latest test build, have a weapon, attack someone, weapon not getting selected

**Comment by superblaubeere27** [comment]
Wait you have to have the weapon in your hotbar. Do you have it?

**Comment by yorik100** [comment]
Seems like axe randomly got removed from my autoslot, oopsie

**Comment by yorik100** [comment]
> 
> 
> Wait you have to have the weapon in your hotbar. Do you have it?

It works back again (no idea why)

**Comment by yorik100** [comment]
Nevermind, not working with killaura

**Comment by kawaiinekololis** [comment]
It's working for me even with killaura ... but the enemy receives no damage

**Comment by kawaiinekololis** [comment]
https://github.com/CCBlueX/LiquidBounce/commit/798aa568378cf75d33a7ba025da732eaf6902591
https://axolotl.vip/3NM8MGFT.mp4?key=227uA4BXCxWlNx

maybe recheck now... changed some stuff and added a new option.

**Comment by yorik100** [comment]
> 
> 
> [CCBlueX/LiquidBounce@798aa56](https://github.com/CCBlueX/LiquidBounce/commit/798aa568378cf75d33a7ba025da732eaf6902591)
> https://axolotl.vip/3NM8MGFT.mp4?key=227uA4BXCxWlNx
> 
> maybe recheck now... changed some stuff and added a new option.

https://streamable.com/oso00 idk, it worked in like b68

**Comment by yorik100** [comment]
(It is fixed now)
