### ISSUE TITLE
[BUG] MotionNCP Step issues

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce-Issues#3595]
https://youtu.be/AcmYx6N9V9M

**Comment by kawaiinekololis** [comment]
It could be improved. The issue is that the client is trying to figure out which block your going to step next.
https://axolotl.club/Rw5XDtgyiqEbn6/t2pynaNW.mp4

**Comment by Teals53** [comment]
@kawaiinekololi its fixed ?

**Comment by Teals53** [comment]
bruh xD
