### ISSUE TITLE
[BUG] Switch aura breaks the aura on some cases

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce-Issues#3596]
**Describe the bug**
https://streamable.com/xhgzq
https://streamable.com/pq0xn (already posted this but reposting it)

**To Reproduce**

**Screenshots**

**Additional information:**
 - LiquidBounce Build Version [e.g. b61]
 - Minecraft Version [e.g. 1.8.9]

**Comment by apexCode1337** [comment]
Yeah I got that bug too
