### ISSUE TITLE
[BUG]killaura weird aiming when standing still

### ISSUE THREAD

**Issue by Lytexx** [CCBlueX/LiquidBounce-Issues#3608]
happens with all target modes
https://streamable.com/lgmib

**Comment by yorik100** [comment]
Doesn't happen with me

**Comment by superblaubeere27** [comment]
Your settings?

**Comment by Lytexx** [comment]
![image](https://user-images.githubusercontent.com/28214667/75778409-045e1000-5d58-11ea-8d74-674ca1df5c4a.png)
