### ISSUE TITLE
[FEATURE]Improve Fucker Rotations

### ISSUE THREAD

**Issue by Lytexx** [CCBlueX/LiquidBounce-Issues#3631]
![image](https://user-images.githubusercontent.com/28214667/77228309-b7b36b00-6b86-11ea-833e-5e5727603ad1.png)

^

**Comment by superblaubeere27** [comment]
This image doesn't tell us anything

**Comment by Lytexx** [comment]
Sry its hard to make a video on my laptop its targeting the cobweb thats what i was trying to say

**Comment by 1zun4secondary** [comment]
https://github.com/CCBlueX/LiquidBounce-Issues/issues/3395
