### ISSUE TITLE
[FEATURE] .target or a .focus for killaura and enchanted nametags

### ISSUE THREAD

**Issue by Cosmo1440** [CCBlueX/LiquidBounce-Issues#3640]
When using kill aura on some servers the anticheat detects when snapping onto a lot of people(ex. a crowd of people in pvp) and the anticheat will slow the hits or flag. Adding a .focus (player) or .target (player) would help this situation in getting the fastest possible kill aura. Using .focus and .target basically focuses them over anyone else in your kill aura range, but if they aren't in range then it will kill anyone.(.enemy player  would work as well as well as putting red names)
If there is an additional fix already in the client, someone let me know! Thanks

**Additional context**
Also putting enchants on nametags would be nice as well!

**Comment by yorik100** [comment]
Adding a .enemy (like a .friend) would be better, it'd focus the enemy people and show them in red in ESP

**Comment by 1zun4secondary** [comment]
https://github.com/CCBlueX/LiquidBounce-Issues/issues/3293
