### ISSUE TITLE
[BUG] Paralyze dont work

### ISSUE THREAD

**Issue by Tcm9** [CCBlueX/LiquidBounce-Issues#3682]
**Describe the bug**

There is no situation where paralysis works. 
Not even on vanilla.
Can you make it work on Vanilla?
If not, it can actually be removed.

**Additional information:**
 - OS: Windows
 - LiquidBounce Build Version B72
 - Minecraft Version 1.8.9

**Comment by kawaiinekololi** [comment]
https://github.com/CCBlueX/LiquidBounce/commit/1e5c1dfb31f1313ce129beed07f8e2ec9c1fe86e
I removed it.

**Comment by Teals53** [comment]
F
