### ISSUE TITLE
Convert all Non-Mixin classes to Kotlin

### ISSUE THREAD

**Issue by NurMarvin** [CCBlueX/LiquidBounce-Issues#3733]
Currently the LiquidBounce source code is a big mess of Java & Kotlin code.
While using Java in some parts, namely the Mixins, is inevitable, it would be at least nice to convert all other parts into Kotlin.
Currently around 55% of the lines of code in LiquidBounce are still written in Java, with ~12% being made up of the code in the Mixins classes.
The ultimate goal would be to bring down the Java portion of the code down to only the Mixins classes.
This issue is to keep track of progress towards this goal and should be mentioned in any commits regarding the conversion of Java to Kotlin files.

**Comment by Teals53** [comment]
marco ripping issues XD
