### ISSUE TITLE
[IMPROVE] AllACInvMove

### ISSUE THREAD

**Issue by TheFleksisCekcu** [CCBlueX/LiquidBounce-Issues#3767]
So, canceling 2 packets can bypass ALL ANTICHEATS.
My code: https://hastebin.com/utunenuveg.cpp

**Comment by superblaubeere27** [comment]
Can you make a PR out of this?

**Comment by TheFleksisCekcu** [comment]
What is PR?

**Comment by superblaubeere27** [comment]
Pull Request

**Comment by TheFleksisCekcu** [comment]
Uhm... I cant pull request in CCBlueX/LiquidBounce

**Comment by TheFleksisCekcu** [comment]
When im pressing "New Pull Request" it redirects me to compare...

**Comment by superblaubeere27** [comment]
Yes because you haven't made any changes on your Fork. I'd recommend watching a YouTube tutorial about Git and GitHub

**Comment by TheFleksisCekcu** [comment]
Thats my new account and i cant make anymore with it

**Comment by yorik100** [comment]
> 
> 
> Can you make a PR out of this? And isn't it detected if you do something in the inventory without having it opened?

1.9+ clients don't send inv packets afaik or it's 1.12+ clients idk

**Comment by TheFleksisCekcu** [comment]
wdym

**Comment by TheFleksisCekcu** [comment]
I dont understood about inv packets, lol

**Comment by CzechHek** [comment]
> Can you make a PR out of this? And isn't it detected if you do something in the inventory without having it opened?

When you do something in inventory, stop the player, send inv open packet and then inv close packet.

**Comment by aftery142** [comment]
> 
> 
> > Can you make a PR out of this? And isn't it detected if you do something in the inventory without having it opened?
> 
> When you do something in inventory, stop the player, send inv open packet and then inv close packet.

pretty sure this can be detected easily

**Comment by CzechHek** [comment]
What about slowly stopping like legit, randomly delaying the invopen packet, delaying inv action packet and then randomly delaying invclose packet?

**Comment by yorik100** [comment]
> 
> 
> > > Can you make a PR out of this? And isn't it detected if you do something in the inventory without having it opened?
> > 
> > 
> > When you do something in inventory, stop the player, send inv open packet and then inv close packet.
> 
> pretty sure this can be detected easily

Only for 1.8 clients
