### ISSUE TITLE
[BUG]Block animation doesnt show

### ISSUE THREAD

**Issue by Vatech1608** [CCBlueX/LiquidBounce-Issues#3839]
I cant see blocking animation in killaura but slowing without noslow, this problem started after b73 update.
https://www.youtube.com/watch?v=be8peMkp4eY
- OS: [Windows 10]
 - LiquidBounce Build Version [b73]
 - Minecraft Version [1.8.9]

**Comment by Aleaf-Egemen** [comment]
Maybe caused because of your scripts ?

**Comment by lolmc1982** [comment]
do you installed any forge mod?
if u have,delete it

**Comment by Emreploit** [comment]
No i havent mods,scripts

**Comment by lolmc1982** [comment]
Try to remove lb mod,download new jar file in the website

**Comment by Faabyy** [comment]
i think its because you have "noswing" on maybe?

**Comment by Litely1222** [comment]
> i think its because you have "noswing" on maybe?

no
