### ISSUE TITLE
[BUG]Idk what name for this bug..

### ISSUE THREAD

**Issue by lolmc1982** [CCBlueX/LiquidBounce-Issues#3843]
**Describe the bug**
when using killaura
open the clickgui(or chat )
it will spam holding item packet
https://streamable.com/qg9lap

it very important
iam using my hpxautoblock script (it send iteminusecount to the server)
but it spam holding item packet make me get banned on hypixel
https://streamable.com/sczxxe (watch full video)

https://forums.ccbluex.net/topic/20/hypixel-autoblock-helper (hypixel autoblc scrit)

**Additional information:**
 - OS: Windows 10 2004
 - LiquidBounce Build Version: Lastest nightly build
 - Minecraft Version : 1.8.9

**Comment by aftery142** [comment]
that's your fake autoblock being fake

**Comment by lolmc1982** [comment]
https://streamable.com/
sczxxe

**Comment by aftery142** [comment]
> 
> 
> that's your fake autoblock being fake

**Comment by aftery142** [comment]
![image](https://user-images.githubusercontent.com/41885049/85556503-19d1af80-b651-11ea-82c8-7421c0144a64.png)
- [ ] bug
- [x] not a bug
