### ISSUE TITLE
[BUG] Fastuse and Sneak bugs

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce-Issues#3874]
Fastuse instant mode not working and sneak vanilla mode reset itself after server change your map so u r not sneaking anymore u need close and open that again but in switch mode its alwasy work

**Comment by Litely1222** [comment]
fastuse instant work for me

**Comment by Teals53** [comment]
> fastuse instant work for me

but its not work for me from latest dev build

**Comment by Teals53** [comment]
which one is duplicate
