### ISSUE TITLE
[FEATURE] Chunk Caching

### ISSUE THREAD

**Issue by Tcm9** [CCBlueX/LiquidBounce-Issues#3879]
**Describe your feature request.**
Saves the loaded chunks so that the world does not have to be reloaded when entering
It should be possible to set the cache size

**Comment by 1zun4secondary** [comment]
I'm not sure why it should be useful to cache chunks?

**Comment by SenkJu** [comment]
I'm pretty sure Minecraft already does some chunk caching.
