### ISSUE TITLE
[FEATURE] About CustomBuilds

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce-Issues#3881]
in the forums i see some custom builds of liquidbounce and this builds have completed things who issued here like inventorymove bypass more scaffold options with better bypass  and customization also more speed-fly-step-velocity bypass types for new version of anti cheats and more inventorycleaner options like MaxXXX options and clean option etc also visual option for criticals like i say before who issued here
some screenshots
![image](https://user-images.githubusercontent.com/13446881/88715076-61eb6280-d126-11ea-8199-9b3072299e9e.png)
![image](https://user-images.githubusercontent.com/13446881/88715349-79c2e680-d126-11ea-99ff-b809dfd01ec0.png)
![image](https://user-images.githubusercontent.com/13446881/88715972-02418700-d127-11ea-8356-13266322e306.png)
![image](https://user-images.githubusercontent.com/13446881/88716007-0cfc1c00-d127-11ea-85c6-f4d1083ff3c2.png)
![image](https://user-images.githubusercontent.com/13446881/88716026-15545700-d127-11ea-847b-66c6bf65b85c.png)

also some knowladge scripts can addable directly into lb source like SuperKB BetterCriticals AutoGapple MoreStrafe SoulAim etc (bcs the are made for scriptapiv1 or need improvement)

**Comment by Teals53** [comment]
From BestNub, IdkWhoMe and JustAnotherBannedUser

**Comment by lolmc1982** [comment]
IdkWhoMe is 
 JustAnotherBannedUser

**Comment by Teals53** [comment]
> IdkWhoMe is
> JustAnotherBannedUser

ok

**Comment by Lytexx** [comment]
i dont get what you want to say with this

**Comment by Teals53** [comment]
> i dont get what you want to say with this

so i mean these stuff can be contributeable

**Comment by Teals53** [comment]
also this rotations customization need for killaura too like that

![image](https://user-images.githubusercontent.com/13446881/88961178-51b1bf80-d2ad-11ea-8379-cccc87e84787.png)

**Comment by superblaubeere27** [comment]
Ok. Why do you post this forum entry in this Issue-Tracker?

**Comment by Teals53** [comment]
> Ok. Why do you post this forum entry in this Issue-Tracker?

For show people ?

**Comment by Teals53** [comment]
for add milestone

**Comment by Teals53** [comment]
for remember this to u about make this better

**Comment by Teals53** [comment]
for for for

**Comment by AtjonTV** [comment]
Just to throw it in, @Teals53 I recommend asking the people that made this in the Forums to submit the changes to the devs so that they can add what was already made.

This way those features can be added faster to the official client build ;D

**Comment by Teals53** [comment]
> Just to throw it in, @Teals53 I recommend asking the people that made this in the Forums to submit the changes to the devs so that they can add what was already made.
> 
> This way those features can be added faster to the official client build ;D

Thats already what i am trying to do xd

**Comment by AtjonTV** [comment]
Yes, but this issue is useless in that sense as it does not make them submit the changes faster, does it? ;D

**Comment by Teals53** [comment]
They can be filter those stuff

**Comment by TheFleksisCekcu** [comment]
wtf(im idkwhome)

**Comment by Teals53** [comment]
> wtf(im idkwhome)

i mean those stuff can be addable into the offical lb build after filtered something idk

**Comment by Teals53** [comment]
rip
