### ISSUE TITLE
[FEATURE] hypixel autoblock

### ISSUE THREAD

**Issue by Waterbuscus1** [CCBlueX/LiquidBounce-Issues#3886]
**Describe your feature request.**
AN AUTOBLOCK THAT ACTUALLY WORKS FOR HYPIXEL

**Additional context**

**Comment by Teals53** [comment]
then open it ?

**Comment by 1zun4secondary** [comment]
AutoBlock is already working, but not with NCP mode NoSlow enabled. https://github.com/CCBlueX/LiquidBounce-Issues/issues/3873
