### ISSUE TITLE
[BUG] Bugs from latest nightly

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce-Issues#3900]
![image](https://user-images.githubusercontent.com/13446881/90986536-53109800-e58c-11ea-8d99-8baddf641aa9.png)
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3812
![image](https://user-images.githubusercontent.com/13446881/90986541-602d8700-e58c-11ea-8036-6826fa905387.png)

click scripts and BUM crash xD

edit: no more crash when clicking scripts

**Comment by Teals53** [comment]
and this bug is fixed in this build
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3799

**Comment by Teals53** [comment]
invcleaner freezing sometimes

**Comment by lolmc1982** [comment]
idk when i run 1.12.2 and get crashed

**Comment by Teals53** [comment]
> idk when i run 1.12.2 and get crashed

run with 1.8.9 forge without any mods and scripts etc

**Comment by superblaubeere27** [comment]
which commit are you on?

**Comment by Teals53** [comment]
> which commit are you on?

latest

**Comment by Teals53** [comment]
white stuff fixed last commit

**Comment by Teals53** [comment]
![image](https://user-images.githubusercontent.com/13446881/91647494-046b6e00-ea64-11ea-849a-372be1cc771e.png)
different colors

**Comment by Teals53** [comment]
weird bug when i click buttons
![image](https://user-images.githubusercontent.com/13446881/91647538-86f42d80-ea64-11ea-9d60-c58a5ac1ab5c.png)

**Comment by Teals53** [comment]
idk why but invcleaner and autoarmor fucked up freezing always or trying to wear armor but they cant and just spamming clientside

**Comment by Teals53** [comment]
@kawaiinekololi can u look at that these stuff ?

**Comment by Teals53** [comment]
https://github.com/CCBlueX/LiquidBounce/commit/afafda7bfa4f1949ee51398123498af686208832

**Comment by Teals53** [comment]
maybe its closed bcs i put multiple issues here now im making one topic per issue
