### ISSUE TITLE
[FEATURE] A new lightweight and beautiful shader background

### ISSUE THREAD

**Issue by kawaiinekololi** [CCBlueX/LiquidBounce-Issues#3931]
We know a lot of people with not that good computers are always telling us that the background is so laggy, so we decided to change to something new and I was able to find something very simple but beautiful.
![](https://i.imgur.com/opvO43x.png)

**Comment by Teals53** [comment]
cool af

**Comment by hahayesfun** [comment]
Pretty cool I would say, but I think it could be something better

**Comment by kawaiinekololi** [comment]
https://github.com/CCBlueX/LiquidBounce/commit/2cb2617e777209a0fb99eb5047b52c0449f8fc3a
