### ISSUE TITLE
[FEATURE] Split up killaura autoblock into modes

### ISSUE THREAD

**Issue by kawaiinekololi** [CCBlueX/LiquidBounce-Issues#3943]
**Describe your feature request.**

**Additional context**

**Comment by Teals53** [comment]
so just autoblock mean packet and with interact mean aftertick ?

**Comment by Teals53** [comment]
anyway i check that now so now we have two different mode also can u explain these modes ? so whats these two modes mean ? about bypass etc

**Comment by Teals53** [comment]
ok delayed block mean after tick
