### ISSUE TITLE
BlockOverlay sieht bei manchen Sachen komisch aus

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce-Issues#45]
Wenn man **BlockOverlay** aktiv hat, und auf **Treppen** guckt, wird nur eine kleine Ecke angezeigt.
Bitte behebt das, danke.

Und PS: Wäre cool wenn man mehrere Farben auswählen könnte (Rot, Grün, Blau, Türkis etc ...)

Liebe Grüße,
FantaCoke.

**Comment by TheRealDAT** [comment]
Die Farben wären echt nice! Und wenns um Farben geht immer Rainbow dazu adden!
