### ISSUE TITLE
ScaffoldWalk für CrackHD

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce-Issues#52]
Bitte macht einen ScaffoldWalk für CrackHD.net

Die haben eine modifizierte AAC Version

**Comment by Marco-MC** [comment]
Sollte mit dem AACAdditionPro Scaffold den ich eingebaut habe in der b24 funken. Teste ich gleich mal.

**Comment by Marco-MC** [comment]
Bypasst... c:
