### ISSUE TITLE
AntiSpam Modul

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce-Issues#53]
Macht bitte ein Modul welches Nachrichten im Chat nicht erneut anzeigt (Clientside), sondern dahinter ein [x2], [x3] undso macht ;)

**Comment by Marco-MC** [comment]
Ich habe versucht es einzubauen, nur hatte ich sehr große Probleme damit da das ChatSytem von Minecraft komplett unnötig "komplex" ist... Ich hatte OpenGL Fehler probleme die ich auch in den Griff bekommen habe aber ich habe jetzt darin 1h investiert und habe kein nerv mehr daran weiter zu arbeiten. Zwar werden warscheinlich irgendwelche behinderten kommen und sagen das ist eZ, aber wenn man bei dem ChatSystem von mc net durchsteigt ist es nicht eZ. Sorry!
