### ISSUE TITLE
Mehrere Schriftarten für den Client zur Auswahl

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce-Issues#54]
Macht bitte mehrere Schriftarten in den Client hinein, sodass jeder eine lieblings Schrift hat.

Oder macht einen Schrift-Selector im Main Menü, womit man Schrift Dateien auswählen kann.

**Comment by Marco-MC** [comment]
Wäre möglich, aber das Problem ist das dass alles nicht mit einer Schriftart zusammen arbeitet und für verschiedene Fonts verschiedene Werte etc und deswegen machen wir das nicht.
