### ISSUE TITLE
Mehr Config-Optionen

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce-Issues#56]
Macht bitte ein .config Befehl, der das gleiche wie .settings macht.

Macht bitte mehr Configs (OldAAC [1.9.10], OldNCP, NewestAAC)

Macht es bitte so, dass man sich eigene Configs erstellen kann, die dann laden, speichern und editieren kann.

**Comment by Marco-MC** [comment]
1. Ja können wir machen.

2. Wenn wir Zeit haben.

3. Giebt es bereits: .localsetting <load/save>
