### ISSUE TITLE
Durchsichtige ArrayList

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce-Issues#57]
Wie der Titel es schon sagt, sollte es meiner Meinung nach eine durchsichtige ArrayList geben, oder zumindest Anpassungsmöglichkeiten die Farbe der ArrayList und der ArrayList Box zu ändern (inkl. Opacity)

Liebe Grüße,
FantaCoke.

**Comment by Marco-MC** [comment]
Ich habe ausgetestet wie eine durchsichtige Array aussieht und das sieht echt schlecht aus. .-.
Das wird daher nicht in die b24 kommen. Sorry!
