### ISSUE TITLE
Add RayCast Option

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce-Issues#59]
Auf MCCentral (mc-central.net) wird man sehr häufig wegen KillAura gekickt.
Macht bitte eine Config dafür, oder einen entsprechenden Bypass.

Die haben AAC 3.0.4 (wahrscheinlich modifiziert).

**Comment by TheRealDAT** [comment]
Ich glaub dafür muss man die Legitaura benutzen außer es kommt ein Update bin mir nicht sicher. Aber selbst mit "schlechten/niedrigen" Killaura Einstellungen wird man gekickt.

**Comment by RealFantaCoke** [comment]
Nein, weil einige andere Clients die ich kenne haben es auch geschafft.

**Comment by Marco-MC** [comment]
Es ist nicht so leicht die KillAura detection von AAC zu bypassen.

> Heuristics Check
Wir haben diesen Check schon so gut wie komplett gebypasst. Der Check wirft bei der LiquidBounce KillAura sogut wie nichts ab.

> KillAura Check
Flaggt die KillAura... Kp... Der Check ist auch der Grund wieso man gekickt wird bei der LiquidBounce Aura. Der Check sollte relativ leicht fixbar sein, aber ich muss erstmal schauen was der Check überhaupt checkt.

**Comment by Marco-MC** [comment]
Wir haben leider bisher noch nicht geschafft die KillAura für AAC default configs komplett zu bypassen... :(
Sobald wir auf unserem TestServer wieder AAC haben, kann ich warscheinlich besser die Aura bypassen aber derzeit tja... Ist das leicht kacke, da ich nicht weiß für was die KillAura geflaggt wird. Die Heuristics sind es auf jedenfall nicht, aber der normale KillAura Check flaggt die lb aura bei Spielern.
Auf jedenfall habe ich wenigstens nen AACAdditionPro InventoryHit Bypass eingebaut https://github.com/CCBlueX/LiquidBounce-Issues/issues/108
Und HurtTime Option auch https://github.com/CCBlueX/LiquidBounce-Issues/issues/117

**Comment by Marco-MC** [comment]
Wir wissen nun wie der KillAura Check funkt, aber diesen Check zu bypassen ist nicht grade leicht wenn man kein super Mathematiker ist. xd Nein Spaß, muss mich nur eigentlich tikkel mit Vektoren besser auseinander setzen etc.

**Comment by Marco-MC** [comment]
So... Ich habe jetzt eine RayCast Option hinzugefügt, womit man lange auf MineSucht, CrackHD etc spielen kann. :)
Ist also jetzt auch abgehakt. Will noch etwas dran arbeiten, aber bisher klappt es sehr, sehr gut.
