### ISSUE TITLE
Little Helper

### ISSUE THREAD

**Issue by TheRealDAT** [CCBlueX/LiquidBounce-Issues#61]
Ein kleines Skin model wie in Necrum das anzeigt ob ein gegner neben dir ist oder deine Rüstung.

**Comment by RealFantaCoke** [comment]
Wenn schon, dann bitte aber auch deaktivierbar.

**Comment by TheRealDAT** [comment]
Ja ein Modul einfach

**Comment by WistarWolf** [comment]
Oder eine Hud Einstellung das es z.B. unter der TabGUI angezeigt wird und wenn man die TabGUI nicht aktiviert hat das es dann unter der WaterMark angezeigt wird würde ich cool finden

**Comment by Marco-MC** [comment]
Added.
