### ISSUE TITLE
.username

### ISSUE THREAD

**Issue by TheRealDAT** [CCBlueX/LiquidBounce-Issues#62]
Dass der Name vom alt im chat steht (also wie .help im chat) trotz nameprotect.

**Comment by RealFantaCoke** [comment]
Hey,

den aktuellen Username kannst du auch im Alt-Manager sehen.
Der Befehl wäre unnötig und würde schlicht und einfach die Performance runter ziehen.

Von meiner Seite aus: #Abgelehnt

Liebe Grüße,
FantaCoke.

**Comment by FlorijonG** [comment]
Hey RealFantaCoke,

Das entscheidet immer noch das CCBlueX Team und nicht du!

**Comment by Marco-MC** [comment]
Also... Ich werde das einbauen, finde es aber persöhnlich ebenfalls relativ unnötig aber da die Performance dadurch nicht runter geht bau ich es ein. :)
