### ISSUE TITLE
BlackHotbar

### ISSUE THREAD

**Issue by FlorijonG** [CCBlueX/LiquidBounce-Issues#63]
Eine lange Hotbar die von unten links bis unten rechts geht(drinnen steht Ping, FPS, Server IP, Potion effects usw.  Mit einem Mode im Hud Module aktivierbar.

**Comment by RealFantaCoke** [comment]
Hey,

dein Vorschlag existierte bereits in früheren Versionen, jedoch wurde es dann entfernt weil der Entwickler der Meinung war dass es hässlich aussehen würde.

Du könntest allerdings dein Vorschlag so bearbeiten, dass Sie (die Entwickler) einen Befehl bzw. eine Option in der HUD einführen, womit man anschließend die Hotbar "switchen" (wechseln) kann.

Liebe Grüße,
FantaCoke.

**Comment by FlorijonG** [comment]
Ließ das dir nochmal durch und da steht dass man dass Deaktivieren kann oder Aktivieren kann im Hud Module sowie die derzeitige BlackHotbar mode.

**Comment by FlorijonG** [comment]
z.B.: Hud(Module Rechtsklicken) --- LargHotbar

**Comment by TheRealDAT** [comment]
DAS MIT RAINBOW, CUZ LSD PLS

**Comment by WistarWolf** [comment]
Ich hatte diese Idee auch schon aber bei mir wurde sie abgelehnt. Ich hoffe trotzdem das es kommt ^^

**Comment by Marco-MC** [comment]
Werden wir doch nicht einbauen.

**Comment by WistarWolf** [comment]
Warum? :[

**Comment by Marco-MC** [comment]
Nein.

**Comment by WistarWolf** [comment]
:c

**Comment by FlorijonG** [comment]
Wieso denn ?

**Comment by WistarWolf** [comment]
@FlorijonG verstehe ich auch net.... Man könnte es ja (De-)Aktivieren. So wie man es halt will... @FlorijonG und Ich finden es halt nice c:
