### ISSUE TITLE
Im ClickGUI einen neuen "Reiter"

### ISSUE THREAD

**Issue by TheRealDAT** [CCBlueX/LiquidBounce-Issues#67]
Um dort Module die man nicht braucht oder verstecken will zu verstecken. Also das man das dann einfach zuklappt. Und das verschieben über den Chat oder so idk.

**Comment by RealFantaCoke** [comment]
Wenn du dich nicht deutlich ausdrückst, wird es nicht übernommen.

**Comment by TheRealDAT** [comment]
Ein neuer Reiter im ClickGUI so wie Render, Movement, Combat damit man Module die man nicht benutzt dort verstecken kann in dem man den Reiter zuklappt und die ausgewählten Module stehen dann nicht mehr in Movement oder Render. Zum Beispiel: ClickGUI dann mit einem Command im Chat ".hidemodule ClickGUI" Dann wird es nicht meht unter Render angezeigt. Damit das ClickGUI aufgeräumt ist und man könnte auch machen das es auch nichtmehr im ClickGUI drin sein soll.

Besser kann ich es nicht erklären.

Liebe Grüße
Dat

**Comment by Marco-MC** [comment]
Nein, sorry dies werden wir nicht einführen.
