### ISSUE TITLE
Script Library

### ISSUE THREAD

**Issue by TheRealDAT** [CCBlueX/LiquidBounce-Issues#68]
Beispiel für Script(Von Alpha Centauri): http://scripts.alpha-centauri.tk:82/

**Comment by RealFantaCoke** [comment]
Bereits vorhanden: .settings <Settings Name>

**Comment by TheRealDAT** [comment]
Nein eine Seite auf der man alle Settings sieht

**Comment by WistarWolf** [comment]
https://github.com/CCBlueX/FileCloud/tree/master/LiquidBounce/autosettings

**Comment by Marco-MC** [comment]
bruh.
