### ISSUE TITLE
Settings List

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce-Issues#69]
Mir würde ein Command fehlen beidem man Die AutoSettngs/LocalSettings Ingame sehen kann. 
.(auto)settingslist und .localsettingslist Dann wird halt Ingame angezeigt welche Auto/localen Settings es gibt.

**Comment by RealFantaCoke** [comment]
Hey,

Genau das wollte ich gerade vorschlagen.
Danke dass du mir die Arbeit abgenommen hast! :)

Liebe Grüße,
FantaCoke.

**Comment by TheRealDAT** [comment]
FantaCoke genau das gleiche hatte ich auch geschrieben nur nicht das es ingame ist...

**Comment by Marco-MC** [comment]
Wir können es bei .localsettings einbauen aber bei .autosettings ist dies nicht so leicht, da wir nicht einfach von GitHub erkennen können was für Dateien dort im Folder liegen. Wir können gucken ob wir da was machen können aber bei .autosettings keine ahnung ob das kommt.

**Comment by Marco-MC** [comment]
Also für LocalSettings habe ich dies nun eingebaut.

**Comment by Marco-MC** [comment]
Für AutoSettings kann ich dies leider nicht einbauen, da ich sonst ne komplette Git API etc einbauen müsste.

**Comment by WistarWolf** [comment]
Ok ^^
