### ISSUE TITLE
Mehr Settings für mehr Server

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce-Issues#70]
Ich würde mir mehr Server für ".settings" wünschen.
Und evtl. auch "OldNCP", "OldAAC" "NewAAC" etc ...

**Comment by Marco-MC** [comment]
Hast du jetzt schon zum Zweitem mal requested...
Auf jedenfall haben wir schon für viele Server settings und können nicht durchgehend alles selbst up to date halten und wenn wir noch mehr settings UND NOCH MEHR UNDE DADAFASD´FASD
ASD. Dann ist nachner Zeit alles outdated...
Auf jedenfall kannst du und auch andere Configs einschicken.
https://github.com/CCBlueX/FileCloud/tree/master/LiquidBounce/autosettings
Einfach per .localsetting save test und dann in den .minecraft/LiquidBounce-1.8/settings gehen und die test datei entweder an uns schicken per Discord oder per Pull Request auf GitHub pushen.
