### ISSUE TITLE
[CONFIG-CHANGE-REQUEST] Scaffold Settings für Cubecraft

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce-Issues#71]
Ich habe dieses "Issue" vorhin schon erstellt, aber es hat sich was geändert.
Cubecraft hat ein "Patch" rausgebracht, welcher die alte Methode teilweise gefixxed hat.

Neue Settings für Cubecraft:

Mode: Normal
Slow?: Yes (true) (Ja)

**Comment by Marco-MC** [comment]
Du kannst auch selbst die Sachen ändern nur so als Info:
https://github.com/CCBlueX/FileCloud/tree/master/LiquidBounce/autosettings
Ich änder das aber mal kurz.

**Comment by RealFantaCoke** [comment]
Okay, das wusste ich noch nicht.
