### ISSUE TITLE
Kleine Sache zu ClientColor

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce-Issues#74]
1. Welche ESPs werden mit ClientColor geändert?
2. Da ClientColor ja ein Modul ist, was passiert wenn man es aktiviert/deaktiviert? Oder ist es Permanent aktiviert?
Und 3. Könntest du einfügen das mit der ClientColor auch diese Farbe geändert wird? http://prntscr.com/eua84k

**Comment by RealFantaCoke** [comment]
Hast du b24 schon? :O

**Comment by WistarWolf** [comment]
Nein aber ich hab das Vid gesehen https://www.youtube.com/watch?v=9I-1n0SO7fk&index=46&list=PLOY8YIiGGn0zth5CeqZTJn-_3mCj9-ung

**Comment by Marco-MC** [comment]
Ich habe ClientColor wieder entfernt und man kann jetzt über das ClickGUI die Farben der clickgui ändern.

**Comment by WistarWolf** [comment]
Ok. Wird dann nur die Farbe vom ClickGUI geändert?
