### ISSUE TITLE
WASD Tasten-Display

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce-Issues#75]
Macht bitte eine Anzeige bzw. eine Option in der HUD womit man eine Anzeige aktivieren -/ deaktivieren kann, welche zeigt welche Keys man gerade gedrückt hat.

Wie in Ambien oder Syntax halt.

Liebe Grüße,
FantaCoke.

**Comment by Marco-MC** [comment]
Nein.
