### ISSUE TITLE
Consolen Screen

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce-Issues#77]
Könnt ihr ein "Display" machen, in dem alle Befehle angezeigt werden, und man dort auch Befehle ausführen kann?

Mit Autovervollständigung bei TAB wäre schon relativ schakusel 👍 

Das ganze Ingame, damit man sozusagen eine "moderne Oberfläche" hat.

Liebe Grüße,
FantaCoke.

Rückfragen? Einfach kommentieren.

**Comment by Marco-MC** [comment]
Komplett unnötig.
