### ISSUE TITLE
Keystrokes

### ISSUE THREAD

**Issue by FlorijonG** [CCBlueX/LiquidBounce-Issues#80]
Währe cool wenn man ein Keystrokes habe könnte der aber deaktivierbar ist also im Hud Module.

**Comment by WistarWolf** [comment]
Diese Idee wurde schon abgelehnt ;) https://github.com/CCBlueX/LiquidBounce-Issues/issues/75

**Comment by FlorijonG** [comment]
hab es grade gesehen XD
