### ISSUE TITLE
ClickGUI Module Einstellungen geordneter

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce-Issues#81]
Bei den Module z.B. Speed wenn man rechtsklick darauf macht öffnen sich ja die Einstellungen von Speed. Und das dann Types dar steht und unten drunter die ganzen Speed Einstellungen. Wenn man rechtsklick auf Types macht das sich neben oder unter Types nochmal eine Category öffnet bei der dann die ganzen Speed Modes stehen. Und das halt noch bei anderen Modulen. Wäre nice aber müsst ihr nicht einbauen.

**Comment by FlorijonG** [comment]
Wie meinst du das also z.B.: Speed Rechtsclicken- BHop- und dann kommen die bhop Speeds ?

**Comment by WistarWolf** [comment]
Ne ich meine: Speed Rechtsklick -> Modes/Types Rechtsklick-> und dann kommen die ganzen Speed Modes entweder unter oder neben Modes/Types

**Comment by TheRealDAT** [comment]
Die Idee ist gut aber nicht mit Modes das ist unnötige Platzverschwendung. Entweder so wie es @FlorijonG beschrieben hat oder mit Anticheats z.B. Spped/AAC/AACBhop, AACOnground und das auch für NCP und so.
