### ISSUE TITLE
Nickname für Freunde

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce-Issues#91]
Könnte ihr machen das wenn man .friend add eingibt das man dann halt .friend add [Name] alias [AliasName] eingeben muss? z.B. .friend add xGamerHD alias &4Kek das er dann als Kek in rot angezeigt wird. Bei .friend list wird dann halt [Name] alias [AliasName] angezeigt. Und nach her im .minecraft LiquidBounce Ordner halt noch änderbar. (Die Idee habe ich von einem Client Names Chronic 1.6)

**Comment by Marco-MC** [comment]
Added.

**Comment by WistarWolf** [comment]
Nice :')

**Comment by Marco-MC** [comment]
Added support for the old friend files

**Comment by WistarWolf** [comment]
Ok
