### ISSUE TITLE
Infos

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce-Issues#97]
Marco, ich weiß dass du findest das diese Infos, ein kleines Logo und die LarghHotbar hässlich aussehen. In den Version wo es drinnen war (b14) sah es wirklich hässlich aus aber auch nur weil da so wenig Infos wahren meiner Meinung nach. Aber man könnte in den Einstellungen von Hud doch eine LarghHotbar Einstellung machen, eine Logo Einstellung und eine Info Einstellungen und die Leute die es (nicht) haben wollen können es  (de-)aktivieren. Das sind doch nurn paar Zeilen Code, das ist doch nicht zu viel verlangt. Überlege dir bitte nochmal. Ich und FlorijonG wollen z.B. dass das kommt weil der Display sonst so leer ist und wir finden das es gut aussieht. :c Auch wenn du zu 99,9% nein antwortest bitte ich dich es einzubauen. Komm schon Marco-MC :c Auch wenn du so gar kein Bock hast es zu machen weil es deiner Meinung nach scheiße aussieht, bau es doch bitte für Leute ein die es wollen.... Es muss nicht in der b24 kommen aber in den weiteren Versionen wäre es cool von dir wenn es trotzdem kommt :c Bitte :[ Ich wrde mich ziemlich freuen wenn es in den nächsten Version kommt :c

**Comment by Marco-MC** [comment]
NEIN.

**Comment by WistarWolf** [comment]
._.

**Comment by FlorijonG** [comment]
warum ?
