### ISSUE TITLE
FPS Anzeige

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce-Issues#98]
Könntest du einbauen das unter der WaterMark/über der Tablist die FPS angezeigt werden?

**Comment by FlorijonG** [comment]
Ja wie in der b20/19

**Comment by Marco-MC** [comment]
Es wird auch einen Grund gegeben haben, wieso ich die Anzeige entfernt habe und mal F3 zu drücken wird niemanden umbringen. ._.
