### ISSUE TITLE
Add Script Support

### ISSUE THREAD

**Issue by Marco-MC** [CCBlueX/LiquidBounce-Issues#99]

**Comment by Marco-MC** [comment]
LiquidScript Documentation
>> v0.1

// Script Informations
scriptName = "Your ScriptName";
scriptVersion = 0.1;
scriptAuthor = "Me";

// Values			
mc.thePlayer.motionX = double
mc.thePlayer.motionY = double
mc.thePlayer.motionZ = double
mc.thePlayer.jumpMovementFactor = float
mc.thePlayer.posX = double
mc.thePlayer.posY = double
mc.thePlayer.posZ = double
Timer.timerSpeed = float
mc.thePlayer.onGround = true/false
keybind.pressed keyname true/false

// Methods
chat.display text...
chat.send text...
movement.strafe float
mc.thePlayer.jump
mc.thePlayer.swingItem
mc.thePlayer.setPosition = double(x) = double(y) = double(z)
mcfont.drawString = int(x) = int(y) int(color) boolean(shadow) string(text)
End

// Run methods
> methodname

// If checks
if mc.thePlayer.onGround
if mc.thePlayer.isCollided
if mc.thePlayer.isCollidedHorizontally
if mc.thePlayer.isCollidedVertically
if EntityUtils.isMoving
if EntityUtils.hasMotion
if mc.thePlayer.isOnLadder
if mc.thePlayer.isInWeb
if mc.thePlayer.isInWater
if mc.thePlayer.isInLava
if Keyboard.isKeyDown keycode

// Object managing
createObject name object
updateObject name object
deleteObject name
mathObject name1 name2 mathsymbol type
mathObjectNumber name1 nummer mathsymbol type

Use object: $name$

// Event Methodes
onCreate
onEnable
onDisable
onUpdate
onPreMotion
onPostMotion
onDraw2D

// Comment
## Your comment

**Comment by WistarWolf** [comment]
Könntest du zu den Values noch hinzufügen dass man auch die X/Y/Z Coodinaten sieht? Aber nur die Zahl vor dem Komma halt. Und noch eine frage. Wie kann man dort einbauen wo und wie groß z.B. die FPS sind?
